### ISSUE TITLE
vtk_fps input must be integer not decimal in .fst-file

### ISSUE THREAD

**Issue by verlivkra** [OpenFAST/acdc#2]
## Description
I have had an issue in which I was able to run acdc with one set of input files, but it crashing with another set of input files. Specifically, acdc failed to import the input files in one of the cases. After some systematic comparison, I found that if the variable "VTK_fps" in the .fst-file was set to "15.0", acdc failed to read .fst-file and import input file, whereas if the variable was set to "15", acdc is able to import the input files. I don't see why the frame rate has to be an integer, and there was no error message, so it was difficult to track down what was wrong. 

### Steps to reproduce issue

The following input made the simulations crash:

---------------------- VISUALIZATION ------------------------------------------
0                      WrVTK       - VTK visualization data output: (switch) {0=none; 1=initialization data only; 2=animation}
2                      VTK_type    - Type of VTK visualization data: (switch) {1=surfaces; 2=basic meshes (lines/points); 3=all meshes (debug)} [unused if WrVTK=0]
False                  VTK_fields  - Write mesh fields to VTK data files? (flag) {true/false} [unused if WrVTK=0]
15.0                    VTK_fps     - Frame rate for VTK output (frames per second){will use closest integer multiple of DT} [used only if WrVTK=2]

### Current behavior
In the "Model"-tab, there is no list of input files after opening the .fst-file. Furthermore, acdc crashes when trying to run simulations.  

### Expected behavior
When importing an .fst-file, the imported input files should be listed and the simulations should run without crashing.

**Comment by deslaughter** [comment]
@verlivkra Thank you for tracking this down and giving a detailed explanation of what was happening. I apologize for taking so long to respond, several other projects had higher priority. I agree that `15.0` should parse into an integer field since it is an integer. I've modified the code to allow this to work; however, I added the check that the number has to be an integer so `15.1` would still be an error. On the plus side, the code to display the error messages has finally been added, so it should be obvious if this is the case. 

The binaries with these changes are available at https://github.com/OpenFAST/acdc/actions/runs/10014059895.
